---
ID: "dc128a1f-13ac-4345-8d46-227fb50ec365"
Parent: "9c7e0dea-5229-42c9-be2b-d5dd2c8d20c5"
Template: "9c7e0dea-5229-42c9-be2b-d5dd2c8d20c5"
Path: /sitecore/templates/Feature/MyModule/Rendering Parameters/EventContent/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231208T052553Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bemartin@deloitte.com.au
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bemartin@deloitte.com.au
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "12c4d4c0-8d1a-4269-a9c1-b035c85c686d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bemartin@deloitte.com.au
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231208T052553Z
