---
ID: "112d28c1-a155-4baa-8e91-305e97be0c32"
Parent: "95640e47-e842-4423-a63c-b13b5aef028f"
Template: "95640e47-e842-4423-a63c-b13b5aef028f"
Path: /sitecore/templates/Feature/MyModule/EventPromo Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {689A960C-3649-4CE6-A8E7-EC2A15838E1E}
    {95640E47-E842-4423-A63C-B13B5AEF028F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231208T051635Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bemartin@deloitte.com.au
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bemartin@deloitte.com.au
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "20cf4a7b-c3cb-49b7-b7cf-0a0ed1b8e68b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bemartin@deloitte.com.au
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231208T051635Z
