---
ID: "71e877d2-92da-4781-bc58-4c134237fa9b"
Parent: "867c7d78-0434-49e7-89b3-bb20e95bc2f3"
Template: "867c7d78-0434-49e7-89b3-bb20e95bc2f3"
Path: /sitecore/templates/Feature/TAC/Hero Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{3AA0B664-B1FE-46FB-86B3-E1AEE686064A}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231208T044718Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bemartin@deloitte.com.au
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bemartin@deloitte.com.au
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bb9e9630-ab49-4610-9de1-335ad99531e9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bemartin@deloitte.com.au
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231208T044755Z
